name: Build
on:
  push:
    branches:
      - develop
      - release
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - run: |
          npm ci
          npm run release
      - run: |
          npm config set registry https://registry.npmjs.org
          npm publish
        if:  github.ref_name == 'master'
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}